### ISSUE TITLE
`app list` blank error if not logged in

### ISSUE THREAD

**Issue by itowlson** [deislabs/hippo-cli#142] opened 2022-06-14 23:10 UTC
Hippo CLI built from current HEAD, Hippo as installed by the installer.  When I do `hippo app list` and am not logged in, I get `Error:` with no error message.

```
$ ./target/debug/hippo app list
Error:

$ ./target/debug/hippo login
Enter username: ivan
Enter password: [hidden]
Logged in as ivan

$ ./target/debug/hippo app list
[
  {
    "id": "ef57e3cf-0145-49f4-b6e1-66cf77b40b3d",
    "name": "spin-hello-world",
# etc
```

**Comment by bacongobbler** [comment] 2022-06-14 23:59
duplicate of #105

**Closed by bacongobbler** 2022-06-14 23:59 UTC
