### ISSUE TITLE
getting blank error trying to add channel with revision ID

### ISSUE THREAD

**Issue by michelleN** [deislabs/hippo-cli#123] opened 2022-04-07 18:46 UTC
```
src/hippo-cli [main] $ hippo channel add --revision-id spin-hello-world/1.0.0 spin-test "37bae039-8ce7-4105-8252-bf4b6f527ba4"
Error:

src/hippo-cli [main] $ hippo channel add --revision-id 1.0.0 spin-test "37bae039-8ce7-4105-8252-bf4b6f527ba4"
Error:

```

**Comment by michelleN** [comment] 2022-04-07 19:41
probably duplicate of #105

**Comment by bacongobbler** [comment] 2022-04-07 20:01
Yeah, this looks like a duplicate of #105. I'll see if we can improve the error message so at least the user will be informed that they need to sign in. `Error:` isn't very helpful. 😄

**Closed by bacongobbler** 2022-04-07 20:01 UTC
